# Generated by Django 5.0.3 on 2024-03-25 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('valido', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_pre_registro',
            },
        ),
    ]
