# Generated by Django 4.2.2 on 2023-06-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_nome_laboratorios_laboraotrio_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorios',
            old_name='laboraotrio_nome',
            new_name='nome',
        ),
    ]
