# Generated by Django 4.2.2 on 2023-06-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_laboraotrio_nome_laboratorios_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_mes',
            },
        ),
    ]
