# Generated by Django 4.2.2 on 2023-06-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mes',
            old_name='mes',
            new_name='nome',
        ),
    ]
