# Generated by Django 4.2.2 on 2023-06-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_rename_mes_mes_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='mes_id',
            field=models.IntegerField(default=0),
        ),
    ]
