# Generated by Django 4.2.2 on 2023-06-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_mes_mes_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mes',
            old_name='nome',
            new_name='mes',
        ),
    ]
