# Generated by Django 4.2.3 on 2023-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_rename_nome_mes_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
