# Generated by Django 4.2.3 on 2023-07-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_salas_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='nome',
        ),
    ]
