# Generated by Django 4.2.3 on 2023-07-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_remove_salas_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salas',
            old_name='status',
            new_name='reservada',
        ),
    ]
