# Generated by Django 4.2.3 on 2023-07-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_rename_status_salas_reservada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='numero_sala',
            field=models.CharField(max_length=5),
        ),
    ]
