# Generated by Django 4.2.3 on 2023-07-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_alter_salas_numero_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='reservada',
            field=models.CharField(default='Livre', max_length=20),
        ),
    ]
