# Generated by Django 4.2.3 on 2023-07-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_salas_reservada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaslaboratorios',
            name='estado',
            field=models.CharField(default='Livre', max_length=20),
        ),
    ]
