# Generated by Django 4.2.3 on 2023-07-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_alter_reservaslaboratorios_data_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaslaboratorios',
            name='data_reserva',
            field=models.DateField(),
        ),
    ]
