# Generated by Django 4.2.3 on 2023-07-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_rename_numero_sala_reservassalas_nome_sala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservassalas',
            old_name='nome_sala',
            new_name='numero_sala',
        ),
    ]
