# Generated by Django 4.2.3 on 2023-07-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_reservassalas_bloco'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaslaboratorios',
            name='bloco',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservaslaboratorios',
            name='estado',
            field=models.CharField(default='Reservado', max_length=20),
        ),
    ]
