# Generated by Django 4.2.3 on 2023-11-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_periodo_remove_salas_reservada_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='periodo',
            table='tb_periodo',
        ),
    ]
