# Generated by Django 4.2.3 on 2023-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_alter_periodo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocos',
            name='id_bloco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='id_periodo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='id_status',
            field=models.IntegerField(),
        ),
    ]
