# Generated by Django 4.2.3 on 2023-11-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_alter_blocos_id_bloco_alter_periodo_id_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorios',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.blocos'),
        ),
    ]
