# Generated by Django 4.2.3 on 2023-11-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_alter_reservaslaboratorios_bloco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorios',
            name='bloco',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='reservassalas',
            name='bloco',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='reservassalas',
            name='numero_sala',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salas',
            name='bloco',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='Blocos',
        ),
    ]
