# Generated by Django 4.2.3 on 2023-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0028_alter_reservaslaboratorios_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorios',
            name='bloco',
            field=models.CharField(choices=[('A', 'Bloco A'), ('B', 'Bloco B'), ('C', 'Bloco C')], max_length=1),
        ),
    ]
