# Generated by Django 4.2.3 on 2023-11-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0029_alter_laboratorios_bloco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaslaboratorios',
            name='estado',
        ),
        migrations.AlterField(
            model_name='reservaslaboratorios',
            name='bloco',
            field=models.CharField(choices=[('A', 'Bloco A'), ('B', 'Bloco B'), ('C', 'Bloco C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reservaslaboratorios',
            name='periodo',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno'), ('DT', 'Dia Todo')], max_length=20),
        ),
    ]
