# Generated by Django 4.2.3 on 2023-11-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0030_remove_reservaslaboratorios_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocos', models.CharField(max_length=1)),
                ('nome_bloco', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_blocos',
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_periodo', models.IntegerField()),
                ('nome_periodo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_periodos',
            },
        ),
        migrations.AlterField(
            model_name='reservaslaboratorios',
            name='periodo',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=20),
        ),
    ]
