# Generated by Django 4.2.3 on 2023-11-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0032_remove_blocos_blocos_remove_blocos_nome_bloco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocos',
            name='id_bloco',
            field=models.IntegerField(),
        ),
    ]
