# Generated by Django 4.2.3 on 2023-11-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0033_alter_blocos_id_bloco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservasSalas',
        ),
        migrations.DeleteModel(
            name='Salas',
        ),
    ]
