# Generated by Django 4.2.3 on 2023-12-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0036_rename_bloco_blocos_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocos',
            old_name='nome',
            new_name='bloco',
        ),
    ]
