# Generated by Django 4.2.3 on 2023-12-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('reservas', '0037_rename_nome_blocos_bloco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaslaboratorios',
            name='nome_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professores'),
        ),
    ]
