# Generated by Django 4.2.3 on 2024-02-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0038_alter_reservaslaboratorios_nome_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaslaboratorios',
            old_name='nome_laboratorio',
            new_name='laboratorio_id',
        ),
    ]
