# Generated by Django 4.2.3 on 2024-02-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0039_rename_nome_laboratorio_reservaslaboratorios_laboratorio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaslaboratorios',
            old_name='laboratorio_id',
            new_name='laboratorio',
        ),
        migrations.RenameField(
            model_name='reservaslaboratorios',
            old_name='nome_professor',
            new_name='professor',
        ),
    ]
